fix:インデントしているulにはmarginがつかないように
vektor-inc/x-t9 pull request #249
Opened 2024-03-18 07:10 UTC by goutetsuguma

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

https://github.com/vektor-inc/x-t9/issues/247

## どういう変更をしたか？

* このプルリクで変更した事を記載してください

li の直下にul がきた場合は除外するような擬似クラスを追加しました。

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

#### ソースコードについて

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 はそれだけで内容が想像できるものになっているか？紛らわしい命名になっていないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 は既存のコードの命名規則に沿ったものになっているか？

#### プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。
書いていない場合は書かない理由を記載してください。

- [ ] 書けそうなテストは書いたか？

#### その他

- [ ] readme.txt に変更内容は書いたか？
- [ ] Files changed (変更ファイル)の内容は目視でちゃんと確認したか？
- [ ] このチェック項目を機械的にチェックするのではなく本当にちゃんと確認をしたか？
- [ ] レビュワーが確認しないでリリースしてしまっても問題ないレベルまでちゃんと作りこみ・確認をしたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

## レビュワーの確認方法・確認する内容など

リストブロックを配置します。
適当にテキスト項目を6つくらい入れて、適当にいくつかインデントさせます。
インデントされた`<li>`の中の`<ul>`タグにmarginがついていないことを確認してください。

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2024-03-18 07:23 UTC, kurudrive requested changes

2024-03-18 07:23 UTC, kurudrive commented on assets/_scss/_common_margin-vertical.scss
> +:is( ul,ol,dl ):not(li > ul) {
@goutetsuguma 
:not は強いから :where() を付けた方が良いような気がする（・ｗ・

2024-03-19 00:14 UTC, goutetsuguma commented on assets/_scss/_common_margin-vertical.scss
> +:is( ul,ol,dl ):not(li > ul) {
@kurudrive ありがとうございます！修正しました（ li > olの場合もあるので追加しました ）

2024-03-19 00:57 UTC, mtdkei commented
@goutetsuguma 
インデントしているulにはmarginがつかないことを確認しました！
マージしてしまってもいいようでしたら行いますが、マージをしたことがないため、ひとまずコメントのみにしています。

2024-03-19 00:58 UTC, mtdkei reviewed
@goutetsuguma
インデントしているulにはmarginがつかないことを確認しました！
マージしてしまってもいいようでしたら行いますが、マージをしたことがないため、ひとまずコメントのみにしています。

2024-03-21 05:36 UTC, merged