【フロントエンドのみ】個別投稿でサイドバーのh4のデザインを変えられない現象を対応
vektor-inc/x-t9 pull request #252
Opened 2024-03-19 07:11 UTC by mtdkei

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）

## どういう変更をしたか？

以下のような、個別投稿のサイドバーのh4のデザインをスタイルから選択しても背景のグレーが残る現象に対応しました。
![image](https://github.com/vektor-inc/x-t9/assets/21466284/9623d249-6a46-4d8f-bca9-787736d1ee0c)

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

#### ソースコードについて

- [x] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 はそれだけで内容が想像できるものになっているか？紛らわしい命名になっていないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 は既存のコードの命名規則に沿ったものになっているか？

#### プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。
書いていない場合は書かない理由を記載してください。

- [ ] 書けそうなテストは書いたか？

#### その他

- [x] readme.txt に変更内容は書いたか？
- [ ] Files changed (変更ファイル)の内容は目視でちゃんと確認したか？
- [ ] このチェック項目を機械的にチェックするのではなく本当にちゃんと確認をしたか？
- [ ] レビュワーが確認しないでリリースしてしまっても問題ないレベルまでちゃんと作りこみ・確認をしたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど
1. [サイトエディター] > [テンプレート] > [個別投稿] に移動
2. サイドバーのh4を選択し、スタイルから適当なものを選び更新(画像は[二重線 上下線 黒])
![image](https://github.com/vektor-inc/x-t9/assets/21466284/d595afe1-eebc-4e4f-b56f-375ca2479917)
3. フロントエンドで「二重線 上下線 黒」のデザインが適用されました。
![image](https://github.com/vektor-inc/x-t9/assets/21466284/c38c26e7-d625-4b14-a1b7-753577a1cfb3)

今回の変更は、以下の.is-style-main-layout-sidebar select にも影響がある変更です。
```
:where(.is-style-main-layout-sidebar) select {
    width: 100%;
}
```
そのため、サイドバーでセレクトボックスを使う場合にも影響がないことを確認しています。
確認方法としては、以下のようにカテゴリーなどを[ドロップダウンで表示]にした後、
![image](https://github.com/vektor-inc/x-t9/assets/21466284/c5238b1f-be9d-4846-bec5-24206117d537)
横幅が100%になっていることを確認しています。
![image](https://github.com/vektor-inc/x-t9/assets/21466284/55861016-db3e-49a0-9e9c-8734e990e6dc)

## レビュワーの確認方法・確認する内容など
1. [サイトエディター] > [テンプレート] > [個別投稿] に移動します。
2. サイドバーのh4を選択し、スタイルから適当なものを選び更新(画像は[二重線 上下線 黒])
3. フロントエンドで「二重線 上下線 黒」のデザインが適用されました。
4. カテゴリーブロックなどを[ドロップダウンで表示]に設定&更新し、横幅が100%になっているかを確認してください。

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2024-03-19 07:17 UTC, kurudrive requested changes

2024-03-19 07:17 UTC, kurudrive commented on readme.txt
> +Addressed inability to change sidebar h4 design in individual posts
```suggestion
[ Design bug fix ] Addressed inability to change sidebar h4 design in individual posts
```

2024-03-19 07:18 UTC, kurudrive approved these changes

2024-03-21 00:26 UTC, goutetsuguma approved these changes

2024-03-21 00:28 UTC, merged

2024-03-21 00:28 UTC, goutetsuguma commented
修正ありがとうございます！2人目確認しまして、問題ないようでしたのでmargeしました