PaginationのPrev、Nextボタンに余白を追加して調整
vektor-inc/x-t9 pull request #318
Opened 2024-12-09 09:11 UTC by sysbird

## チケットへのリンク / 変更の理由（元のissueがあればリンクを貼り付ければOK）
 X-T9 PaginationのNextボタンに余白がありませんので修正 #312 
 を引き継いでいます

## どういう変更をしたか？
* Prev ボタンの右、Next ボタンの左に余白がないので追加しました

実装者はレビュワーに回す前に以下の事を確認してチェックをつけてください。

#### ソースコードについて

- [ ] 複数の意図の変更 （ 機能の不具合修正 + 別の機能追加など ） を含んでいないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 はそれだけで内容が想像できるものになっているか？紛らわしい命名になっていないか？
- [ ] 関数名 / 変数名 / クラス名 / 保存値名 は既存のコードの命名規則に沿ったものになっているか？

#### プログラムの変更の場合

テストを書かないのは普通ではありません。書けるテストは極力書くようにしてください。
書いていない場合は書かない理由を記載してください。

- [ ] 書けそうなテストは書いたか？

#### その他

- [ ] readme.txt に変更内容は書いたか？
- [ ] Files changed (変更ファイル)の内容は目視でちゃんと確認したか？
- [ ] このチェック項目を機械的にチェックするのではなく本当にちゃんと確認をしたか？
- [ ] レビュワーが確認しないでリリースしてしまっても問題ないレベルまでちゃんと作りこみ・確認をしたか？

## 変更内容について何を確認したか、どういう方法で確認をしたかなど

## レビュワーの確認方法・確認する内容など

## レビュワーに回す前の確認事項

- [ ] このテンプレートのチェック項目をちゃんと確認してチェックしたか？

---

## レビュワー向け

### 確認して変更が反映されていない場合の確認事項

* プルしたか？
* ビルドしたか？
* ビルドしたディレクトリは正しいか（別の開発環境のディレクトリを見ていないか）？
* npm install したか？
* composer install したか？

2024-12-09 10:47 UTC, kurudrive requested changes

2024-12-09 10:47 UTC, kurudrive commented on assets/_scss/_pagenation.scss
> +
@sysbird ありがとうございまっす。
ここ + なしで普通に下記のような感じでいいかなと思うのですがどうでしょう（・ｗ・？

```suggestion
	.wp-block-query-pagination-previous {
		margin-inline-end: .5em;
	}

	.wp-block-query-pagination-next {
		margin-inline-start: .5em;
	}
```

2024-12-09 10:51 UTC, kurudrive requested changes

2024-12-09 10:51 UTC, kurudrive commented on assets/_scss/_pagenation.scss
> +
@sysbird あ、いや、コメントのページナビゲーションも関係するからこれじゃダメかも。
コメントのページ送りでも問題なく表示されるか確認の上、必要に応じて調整よろしくお願いいたします。

2024-12-10 08:25 UTC, sysbird commented on assets/_scss/_pagenation.scss
> +
> ここ + なしで普通に下記のような感じでいいかなと思うのですがどうでしょう

@kurudrive 
あら、これでいけますね
コアの CSS に負けてうまくいかないように見えたのですが、気のせいでした
ありがとうございます！

2024-12-10 08:47 UTC, sysbird commented
@kurudrive 
ご指摘ありがとうございます〜
* マージンを指定する箇所を修正しました
* この修正はコメントのページネーションには影響がなく、確認したところコメントのページネーションはもとから余白が空いてますので(吐き出されてるHTMLの違い?)、ここまでの修正にします

2024-12-10 09:05 UTC, kurudrive approved these changes

2024-12-10 09:05 UTC, kurudrive commented
@sysbird ありがとうございます。マージしますー！

2024-12-10 09:05 UTC, merged